language: csharp
os: osx

env: 
  global: 
    - Configuration=Release
    - LIB_VERSION=1.2
    - NUGET_VERSION=1.2-beta1
    
    
cache:
  directories:
    - downloads

install: 
  - ./build-scripts/changeversion.sh ${LIB_VERSION} ${NUGET_VERSION}

script: 
  - xbuild DT.Xamarin.DGActivityIndicatorView/DT.Xamarin.DGActivityIndicatorView/DT.Xamarin.DGActivityIndicatorView.sln /p:Configuration=Release

after_script:
  - ./build-scripts/pack.sh
  - ./build-scripts/upload.sh ${NUGET_VERSION} ${NUGET_API_KEY}